/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'training-topics': TrainingTopic;
    'training-programs': TrainingProgram;
    'simulation-systems': SimulationSystem;
    'virtual-classrooms': VirtualClassroom;
    news: News;
    'international-guide': InternationalGuide;
    faqs: Faq;
    pages: Page;
    'gallery-albums': GalleryAlbum;
    media: Media;
    'document-files': DocumentFile;
    'library-resources': LibraryResource;
    projects: Project;
    'form-requests': FormRequest;
    users: User;
    'search-index': SearchIndex;
    forms: Form;
    'form-submissions': FormSubmission;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'training-topics': TrainingTopicsSelect<false> | TrainingTopicsSelect<true>;
    'training-programs': TrainingProgramsSelect<false> | TrainingProgramsSelect<true>;
    'simulation-systems': SimulationSystemsSelect<false> | SimulationSystemsSelect<true>;
    'virtual-classrooms': VirtualClassroomsSelect<false> | VirtualClassroomsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    'international-guide': InternationalGuideSelect<false> | InternationalGuideSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'gallery-albums': GalleryAlbumsSelect<false> | GalleryAlbumsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'document-files': DocumentFilesSelect<false> | DocumentFilesSelect<true>;
    'library-resources': LibraryResourcesSelect<false> | LibraryResourcesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'form-requests': FormRequestsSelect<false> | FormRequestsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'search-index': SearchIndexSelect<false> | SearchIndexSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('tr' | 'en' | 'ru') | ('tr' | 'en' | 'ru')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    homepage: Homepage;
    'external-services': ExternalService;
    'simulation-center': SimulationCenter;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'external-services': ExternalServicesSelect<false> | ExternalServicesSelect<true>;
    'simulation-center': SimulationCenterSelect<false> | SimulationCenterSelect<true>;
  };
  locale: 'tr' | 'en' | 'ru';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Thematic areas of the centre. Training programmes link to these topics.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-topics".
 */
export interface TrainingTopic {
  id: number;
  /**
   * Auto-generated from the title if left empty. If you change a published slug, add a 301 in Redirects.
   */
  slug: string;
  order?: number | null;
  featured?: boolean | null;
  /**
   * Calculated automatically. Shows missing locales.
   */
  translationStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  publishedAt?: string | null;
  title: string;
  /**
   * Shown on cards and in search results. Max 400 characters.
   */
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  learningOutcomes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shared vocabulary with the EK-2 digital library. Coordinate before changing.
   */
  category:
    | 'forest-fires'
    | 'integrated-fire-management'
    | 'sfm'
    | 'flr'
    | 'land-degradation'
    | 'climate-change'
    | 'nursery-afforestation'
    | 'silviculture'
    | 'protected-areas'
    | 'nature-conservation'
    | 'gis-rs'
    | 'forest-pests'
    | 'nwfp'
    | 'forest-livelihoods'
    | 'gender'
    | 'capacity-development';
  level?: ('basic' | 'intermediate' | 'advanced' | 'tot')[] | null;
  targetAudience?: string | null;
  /**
   * Used by on-site search and filtering.
   */
  keywords?: string[] | null;
  icon?: (number | null) | Media;
  coverImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  /**
   * Adds a link to the Simulation Centre page (spec 9.3).
   */
  usesSimulation?: boolean | null;
  relatedSimulationSystems?: (number | SimulationSystem)[] | null;
  /**
   * Subject code in the EK-2 library system. Enables the “Publications on this topic” link.
   */
  librarySubjectKey?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Required by WCAG 2.2 AA. Describe what the image conveys.
   */
  alt: string;
  caption?: string | null;
  /**
   * Copyright holder. Required by visibility rules.
   */
  credit?: string | null;
  /**
   * Set automatically for video and PDF uploads.
   */
  mediaType?: ('photo' | 'video' | 'infographic' | 'screenshot' | 'logo' | 'document') | null;
  isDecorative?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * OYMES, BTES and other simulation systems. Page intro lives under Globals.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "simulation-systems".
 */
export interface SimulationSystem {
  id: number;
  /**
   * Auto-generated from the title if left empty. If you change a published slug, add a 301 in Redirects.
   */
  slug: string;
  order?: number | null;
  /**
   * Calculated automatically. Shows missing locales.
   */
  translationStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * e.g. OYMES — Forest Fire Response Training Simulator
   */
  title: string;
  /**
   * e.g. OYMES, BTES
   */
  shortCode: string;
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  useCases?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  benefitsForInternational?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  technicalSpecs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  capacity?: number | null;
  /**
   * Spec 6.5: remote access links for simulations.
   */
  supportsRemote?: boolean | null;
  /**
   * Entry points to the simulation module. Authentication happens on the target system.
   */
  accessLinks?:
    | {
        audience: 'trainer' | 'learner' | 'public';
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  coverImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  /**
   * CDN-served source URL or embed link (spec 6.5 — CDN).
   */
  videos?:
    | {
        title: string;
        url: string;
        poster?: (number | null) | Media;
        /**
         * WCAG 2.2 — captions for video content.
         */
        captionsUrl?: string | null;
        transcript?: string | null;
        id?: string | null;
      }[]
    | null;
  relatedTopics?: (number | TrainingTopic)[] | null;
  usageInTraining?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Announcement, calendar entry and detail page all come from one record.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-programs".
 */
export interface TrainingProgram {
  id: number;
  /**
   * Auto-generated from the title if left empty. If you change a published slug, add a 301 in Redirects.
   */
  slug: string;
  /**
   * Spec 1.6. Editorial workflow. Visibility on the site still requires publishing the record.
   */
  reviewStatus: 'draft' | 'in_review' | 'approved' | 'published';
  /**
   * Drives the calendar badge and the visibility of the Apply button.
   */
  status: 'planned' | 'applications-open' | 'applications-closed' | 'ongoing' | 'completed' | 'postponed' | 'cancelled';
  featured?: boolean | null;
  /**
   * Calculated automatically. Shows missing locales.
   */
  translationStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  publishedAt?: string | null;
  title: string;
  /**
   * e.g. AIFTC-2027-IFM-01. Used by certificate numbers and library links.
   */
  code?: string | null;
  summary: string;
  topics: (number | TrainingTopic)[];
  startDate: string;
  endDate?: string | null;
  durationDays?: number | null;
  durationHours?: number | null;
  deliveryMode: 'in-person' | 'online' | 'hybrid';
  level?: ('basic' | 'intermediate' | 'advanced' | 'tot') | null;
  /**
   * e.g. AIFTC Campus, Antalya. May be empty for online training.
   */
  venue?: string | null;
  /**
   * Language(s) the training is delivered in — independent of the page locale.
   */
  instructionLanguages: ('tr' | 'en' | 'ru')[];
  targetAudience?: string | null;
  /**
   * ISO 3166-1 alpha-2. Leave empty if not applicable.
   */
  participantCountries?: ('TR' | 'AZ' | 'KZ' | 'KG' | 'TJ' | 'TM' | 'UZ' | 'OTHER')[] | null;
  quota?: number | null;
  applicationRequirements?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  applicationDeadline?: string | null;
  applicationTarget?: {
    type?: ('contact' | 'external' | 'portal' | 'email' | 'none') | null;
    url?: string | null;
    /**
     * The portal base URL comes from Site Settings > External Services. Enter only the path.
     */
    portalPath?: string | null;
    email?: string | null;
    contactUnit?: string | null;
  };
  objective?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  learningOutcomes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  schedule?:
    | {
        /**
         * e.g. Day 1 — 12 May
         */
        dayLabel: string;
        sessions?:
          | {
              time?: string | null;
              title: string;
              type?: ('theory' | 'practice' | 'simulation' | 'field' | 'assessment') | null;
              trainer?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  trainers?:
    | {
        name: string;
        titleAndRole?: string | null;
        organization?: string | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  assessmentMethod?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  usesSimulation?: boolean | null;
  simulationSystems?: (number | SimulationSystem)[] | null;
  hasFieldExercise?: boolean | null;
  /**
   * Spec 7.1: the document type must be stated on every training page.
   */
  certificateType: 'certificate' | 'attendance' | 'achievement' | 'tot' | 'project-specific' | 'none';
  certificateConditions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Logo order matters under the visibility rules (10.2).
   */
  issuingBodies?:
    | {
        name: string;
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Small files served directly from the site (announcement annex, programme PDF).
   */
  attachments?: (number | DocumentFile)[] | null;
  /**
   * Collection/tag key in the EK-2 library. Enables the “Training materials” button.
   */
  libraryCollectionKey?: string | null;
  results?: {
    /**
     * Aggregate count only. No participant names are stored on the website.
     */
    participantCount?: number | null;
    summary?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    photos?: (number | Media)[] | null;
    videoUrl?: string | null;
    hadCertificateCeremony?: boolean | null;
    relatedNews?: (number | News)[] | null;
  };
  coverImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Site attachments (programme PDFs, forms, brochures). Videos meant to PLAY in the library belong in the Media library, not here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-files".
 */
export interface DocumentFile {
  id: number;
  title: string;
  /**
   * Spec 13: descriptive information next to download links.
   */
  description?: string | null;
  documentType: 'programme' | 'announcement-annex' | 'form' | 'guide' | 'report' | 'legal' | 'video' | 'other';
  language?: ('tr' | 'en' | 'ru')[] | null;
  version?: string | null;
  /**
   * ENFORCED: the download URL itself is protected by this level. Anything other than Public cannot be downloaded without the matching role, even with the direct link.
   */
  accessLevel: 'public' | 'staff' | 'participants' | 'trainers' | 'internal';
  /**
   * Archived documents disappear from listings; existing links keep working.
   */
  isArchived?: boolean | null;
  license?:
    ('cc-by' | 'cc-by-sa' | 'cc-by-nc' | 'cc-by-nc-nd' | 'cc0' | 'institutional' | 'all-rights-reserved') | null;
  copyrightHolder?: string | null;
  humanFileSize?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  /**
   * Auto-generated from the title if left empty. If you change a published slug, add a 301 in Redirects.
   */
  slug: string;
  /**
   * Spec 1.6. Editorial workflow. Visibility on the site still requires publishing the record.
   */
  reviewStatus: 'draft' | 'in_review' | 'approved' | 'published';
  kind: 'news' | 'announcement';
  category:
    | 'training'
    | 'project'
    | 'cooperation'
    | 'technical-visit'
    | 'workshop'
    | 'training-result'
    | 'publication'
    | 'announcement';
  featured?: boolean | null;
  /**
   * After this date the item leaves the homepage strip but stays in the archive.
   */
  expiresAt?: string | null;
  /**
   * Calculated automatically. Shows missing locales.
   */
  translationStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  publishedAt?: string | null;
  title: string;
  summary: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  coverImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  videoUrl?: string | null;
  relatedTrainings?: (number | TrainingProgram)[] | null;
  relatedTopics?: (number | TrainingTopic)[] | null;
  countries?: ('TR' | 'AZ' | 'KZ' | 'KG' | 'TJ' | 'TM' | 'UZ' | 'OTHER')[] | null;
  attachments?: (number | DocumentFile)[] | null;
  isProjectOutput?: boolean | null;
  project?: (number | null) | Project;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Auto-generated from the title if left empty. If you change a published slug, add a 301 in Redirects.
   */
  slug: string;
  isPrimary?: boolean | null;
  /**
   * Calculated automatically. Shows missing locales.
   */
  translationStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  title: string;
  /**
   * e.g. GCP/SEC/024/TUR
   */
  symbol: string;
  startDate?: string | null;
  endDate?: string | null;
  nationalCounterpart?: string | null;
  partners?:
    | {
        name: string;
        logo?: (number | null) | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  focusCountries?: ('TR' | 'AZ' | 'KZ' | 'KG' | 'TJ' | 'TM' | 'UZ' | 'OTHER')[] | null;
  objective?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  capacityStatement?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  externalUrl?: string | null;
  /**
   * Spec 10.2 — logo order must follow FAO/MAF/OGM visibility rules.
   */
  logos?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Live session rooms. Passwords are visible to admin/editor roles only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "virtual-classrooms".
 */
export interface VirtualClassroom {
  id: number;
  /**
   * Name shown to participants.
   */
  title: string;
  /**
   * The join button appears on this training’s detail page.
   */
  training: number | TrainingProgram;
  /**
   * A closed room shows no join form. Defaults to closed.
   */
  roomStatus: 'active' | 'closed';
  platform: 'jitsi' | 'bigbluebutton' | 'zoom' | 'teams' | 'other';
  startsAt: string;
  endsAt: string;
  /**
   * How early participants may enter before the start time.
   */
  joinWindowMinutes?: number | null;
  /**
   * Shown above the password field. Do NOT put the password here — this text is public.
   */
  instructions?: string | null;
  /**
   * Full URL. Never shown before the access code is verified.
   */
  meetingUrl?: string | null;
  /**
   * Jitsi room name or BigBlueButton meetingID.
   */
  meetingId?: string | null;
  /**
   * Grants moderator rights on the join page.
   */
  moderatorPassword?: string | null;
  /**
   * The code announced to participants; asked for on the join page.
   */
  attendeePassword?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Spec 8.1–8.2. Sections render on one page, each with its own anchor.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "international-guide".
 */
export interface InternationalGuide {
  id: number;
  /**
   * Auto-generated from the title if left empty. If you change a published slug, add a 301 in Redirects.
   */
  slug: string;
  order?: number | null;
  /**
   * Calculated automatically. Shows missing locales.
   */
  translationStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Headings listed in spec 8.1. Icon and ordering derive from this.
   */
  sectionKey:
    | 'about-centre'
    | 'eligibility'
    | 'application'
    | 'language'
    | 'accommodation'
    | 'travel'
    | 'arrival-antalya'
    | 'transfer'
    | 'visa'
    | 'certificate'
    | 'contact'
    | 'practical'
    | 'other';
  title: string;
  /**
   * Shown in the quick-overview cards at the top of the page.
   */
  summary?: string | null;
  /**
   * Use plain, short sentences — most readers are non-native speakers.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image?: (number | null) | Media;
  attachments?: (number | DocumentFile)[] | null;
  countries?: ('TR' | 'AZ' | 'KZ' | 'KG' | 'TJ' | 'TM' | 'UZ' | 'OTHER')[] | null;
  countryNotes?:
    | {
        country: 'TR' | 'AZ' | 'KZ' | 'KG' | 'TJ' | 'TM' | 'UZ' | 'OTHER';
        note: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  links?:
    | {
        label: string;
        url: string;
        /**
         * External links open in a new tab with an accessible warning (WCAG 2.2).
         */
        isExternal?: boolean | null;
        id?: string | null;
      }[]
    | null;
  relatedFaqs?: (number | Faq)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  group:
    'applications' | 'languages' | 'certificates' | 'accommodation' | 'materials' | 'format' | 'simulation' | 'contact';
  order?: number | null;
  /**
   * Calculated automatically. Shows missing locales.
   */
  translationStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Auto-generated from the title if left empty. If you change a published slug, add a 301 in Redirects.
   */
  slug: string;
  pageType: 'home' | 'standard' | 'institution' | 'contact' | 'legal';
  parent?: (number | null) | Page;
  /**
   * Calculated automatically. Shows missing locales.
   */
  translationStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  publishedAt?: string | null;
  title: string;
  subtitle?: string | null;
  heroImage?: (number | null) | Media;
  layout?:
    | (
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            media: number | Media;
            caption?: string | null;
            width?: ('container' | 'wide' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            /**
             * Optional. e.g. “Management”, “History”. Left empty, no heading is shown.
             */
            heading?: string | null;
            items?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statsBlock';
          }
        | {
            /**
             * Optional. e.g. “Management”, “History”. Left empty, no heading is shown.
             */
            heading?: string | null;
            people?:
              | {
                  name: string;
                  role?: string | null;
                  unit?: string | null;
                  photo?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'peopleBlock';
          }
        | {
            /**
             * Optional. e.g. “Management”, “History”. Left empty, no heading is shown.
             */
            heading?: string | null;
            partners?:
              | {
                  name: string;
                  logo?: (number | null) | Media;
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'partnersBlock';
          }
        | {
            /**
             * Optional. e.g. “Management”, “History”. Left empty, no heading is shown.
             */
            heading?: string | null;
            entries?:
              | {
                  year: string;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timelineBlock';
          }
        | {
            heading: string;
            text?: string | null;
            target?: ('internal' | 'library' | 'portal' | 'external') | null;
            /**
             * For library/portal, enter only the path. The base URL comes from Site Settings.
             */
            href?: string | null;
            buttonLabel: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBlock';
          }
        | {
            heading?: string | null;
            faqs?: (number | Faq)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | {
            showMap?: boolean | null;
            showForm?: boolean | null;
            form?: (number | null) | Form;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactBlock';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Spec 12.2 — shown with a consent checkbox before submission.
   */
  consentText?: string | null;
  retentionDays?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-albums".
 */
export interface GalleryAlbum {
  id: number;
  /**
   * Auto-generated from the title if left empty. If you change a published slug, add a 301 in Redirects.
   */
  slug: string;
  albumType: 'photo' | 'video' | 'training-video' | 'promo' | 'webinar' | 'simulation' | 'infographic';
  date?: string | null;
  /**
   * Calculated automatically. Shows missing locales.
   */
  translationStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  title: string;
  description?: string | null;
  coverImage?: (number | null) | Media;
  images?: (number | Media)[] | null;
  videos?:
    | {
        title: string;
        url: string;
        poster?: (number | null) | Media;
        durationSeconds?: number | null;
        /**
         * Recommended by WCAG 2.2.
         */
        captionsUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  relatedTraining?: (number | null) | TrainingProgram;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Catalogue records for library publications. Upload the file under “Site documents” first, then link it here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "library-resources".
 */
export interface LibraryResource {
  id: number;
  /**
   * Auto-generated from the title if left empty. If you change a published slug, add a 301 in Redirects.
   */
  slug: string;
  /**
   * Spec 1.6. Editorial workflow. Visibility on the site still requires publishing the record.
   */
  reviewStatus: 'draft' | 'in_review' | 'approved' | 'published';
  /**
   * Who can see this record. Anything other than Public requires a login. NOTE: this hides the record but does not protect the attached file URL.
   */
  accessLevel: 'public' | 'staff' | 'instructor' | 'trainee';
  /**
   * Drives the filter bar on the library page.
   */
  resourceType:
    'report' | 'technical-guide' | 'workshop-presentation' | 'yearbook-statistics' | 'video' | 'photo-album';
  /**
   * Year only. Put a fuller date in the description if the publication has one.
   */
  publicationYear: number;
  /**
   * Shown at the top of the library listing.
   */
  featured?: boolean | null;
  /**
   * Increments automatically. Not deduplicated — a rough popularity signal.
   */
  downloads?: number | null;
  /**
   * Filled in automatically on creation. Change it if you are entering the record on someone else’s behalf.
   */
  uploadedBy?: (number | null) | User;
  /**
   * Calculated automatically. Shows missing locales.
   */
  translationStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  publishedAt?: string | null;
  title: string;
  /**
   * One or two sentences shown on the card.
   */
  description?: string | null;
  /**
   * The person or team who wrote the publication. Use the field below for the issuing institution. Optional.
   */
  author?: string | null;
  /**
   * The institution that issued the publication, e.g. “FAO”, “General Directorate of Forestry”.
   */
  institution?: string | null;
  /**
   * The language of the publication itself, independent of the site’s interface language.
   */
  language?: ('tr' | 'en' | 'ru')[] | null;
  /**
   * The country or countries the publication concerns. Pick several for regional publications.
   */
  countries?: ('TR' | 'AZ' | 'KZ' | 'KG' | 'TJ' | 'TM' | 'UZ' | 'OTHER')[] | null;
  /**
   * Feeds on-site search. Enter one term per entry; do not repeat the topics above.
   */
  keywords?: string[] | null;
  /**
   * Persistent identifier, written with its prefix, e.g. “DOI: 10.4060/cb1234en”. Leave empty if there is none.
   */
  identifier?: string | null;
  /**
   * Training programmes this publication belongs to.
   */
  relatedTrainings?: (number | TrainingProgram)[] | null;
  /**
   * If the publication is a project output, link the project here.
   */
  relatedProjects?: (number | Project)[] | null;
  /**
   * Drives the thematic filters; same list as the training catalogue.
   */
  topics?: (number | TrainingTopic)[] | null;
  /**
   * Pick from the Media library or Site documents — whichever you uploaded to. Only MP4 (H.264) and WebM play in every browser; MOV plays in Safari only.
   */
  videoFile?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'document-files';
        value: number | DocumentFile;
      } | null);
  /**
   * Hides the download link under the player. Not an access restriction — the file URL stays reachable.
   */
  allowVideoDownload?: boolean | null;
  /**
   * e.g. “45 min”. Shown on the card so visitors know the length before clicking.
   */
  videoDuration?: string | null;
  /**
   * Recommended by WCAG 2.2 (1.2.2). Only .vtt (WebVTT) works in the browser; SRT files will not display.
   */
  captionsUrl?: string | null;
  /**
   * Order follows this list. Each image needs an alt text in its Media record.
   */
  gallery?: (number | Media)[] | null;
  /**
   * Pick from Site documents or the Media library. Size and type are read automatically.
   */
  file?:
    | ({
        relationTo: 'document-files';
        value: number | DocumentFile;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  /**
   * If the publication lives on another institution’s site, enter its URL instead of uploading a file.
   */
  externalUrl?: string | null;
  /**
   * Fill in only for records that link out. When a file is attached the format is read from it automatically.
   */
  fileFormat?: ('pdf' | 'docx' | 'xlsx' | 'pptx' | 'epub' | 'mp4' | 'mp3' | 'zip' | 'html' | 'other') | null;
  /**
   * Only for records that link out. Write it readably, e.g. “4.2 MB”.
   */
  fileSize?: string | null;
  /**
   * Version of the publication, if it has one. Usually left empty.
   */
  version?: string | null;
  /**
   * Terms of use. Leave empty if unsure — an incorrect licence statement binds the institution.
   */
  license?:
    ('cc-by' | 'cc-by-sa' | 'cc-by-nc' | 'cc-by-nc-nd' | 'cc0' | 'institutional' | 'all-rights-reserved') | null;
  /**
   * Fill in when the rights holder differs from the issuing institution.
   */
  copyrightHolder?: string | null;
  /**
   * Optional. Without it the card shows a type badge on a neutral panel.
   */
  coverImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * The Author role cannot publish; records stay as drafts.
   */
  roles?: ('admin' | 'editor' | 'author' | 'viewer')[] | null;
  /**
   * Spec 1.7. Controls which library records the user can see ON THE SITE. Panel permissions are the separate Roles field.
   */
  role: 'admin' | 'staff' | 'instructor' | 'trainee';
  /**
   * Spec 1.7. Accounts other than Approved cannot log in. Public registrations arrive as Pending.
   */
  accountStatus: 'pending' | 'approved' | 'suspended';
  unit?: string | null;
  preferredAdminLanguage?: ('tr' | 'en' | 'ru') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Contact and training application requests. These records contain personal data.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-requests".
 */
export interface FormRequest {
  id: number;
  submissionType: 'contact' | 'training-application';
  /**
   * New records arrive as “Pending”. Mark as “Read” once handled.
   */
  status: 'pending' | 'read';
  fullName: string;
  email: string;
  organization?: string | null;
  country?: ('TR' | 'AZ' | 'KZ' | 'KG' | 'TJ' | 'TM' | 'UZ' | 'OTHER') | null;
  subject?: string | null;
  message: string;
  /**
   * Filled automatically when the visitor arrives from a training page.
   */
  relatedTraining?: (number | null) | TrainingProgram;
  consentAcceptedAt?: string | null;
  /**
   * The notice shown at submission time; unchanged even if the text is later edited.
   */
  consentSnapshot?: string | null;
  /**
   * Indicates which language the reply should be written in.
   */
  locale?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search-index".
 */
export interface SearchIndex {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'pages';
        value: number | Page;
      }
    | {
        relationTo: 'training-programs';
        value: number | TrainingProgram;
      }
    | {
        relationTo: 'training-topics';
        value: number | TrainingTopic;
      }
    | {
        relationTo: 'news';
        value: number | News;
      }
    | {
        relationTo: 'simulation-systems';
        value: number | SimulationSystem;
      }
    | {
        relationTo: 'faqs';
        value: number | Faq;
      }
    | {
        relationTo: 'library-resources';
        value: number | LibraryResource;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * Unused. See System > Form submissions for contact and application requests.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'news';
          value: number | News;
        } | null)
      | ({
          relationTo: 'training-programs';
          value: number | TrainingProgram;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'training-topics';
        value: number | TrainingTopic;
      } | null)
    | ({
        relationTo: 'training-programs';
        value: number | TrainingProgram;
      } | null)
    | ({
        relationTo: 'simulation-systems';
        value: number | SimulationSystem;
      } | null)
    | ({
        relationTo: 'virtual-classrooms';
        value: number | VirtualClassroom;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'international-guide';
        value: number | InternationalGuide;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'gallery-albums';
        value: number | GalleryAlbum;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'document-files';
        value: number | DocumentFile;
      } | null)
    | ({
        relationTo: 'library-resources';
        value: number | LibraryResource;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'form-requests';
        value: number | FormRequest;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'search-index';
        value: number | SearchIndex;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-topics_select".
 */
export interface TrainingTopicsSelect<T extends boolean = true> {
  slug?: T;
  order?: T;
  featured?: T;
  translationStatus?: T;
  publishedAt?: T;
  title?: T;
  summary?: T;
  description?: T;
  learningOutcomes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  category?: T;
  level?: T;
  targetAudience?: T;
  keywords?: T;
  icon?: T;
  coverImage?: T;
  gallery?: T;
  usesSimulation?: T;
  relatedSimulationSystems?: T;
  librarySubjectKey?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-programs_select".
 */
export interface TrainingProgramsSelect<T extends boolean = true> {
  slug?: T;
  reviewStatus?: T;
  status?: T;
  featured?: T;
  translationStatus?: T;
  publishedAt?: T;
  title?: T;
  code?: T;
  summary?: T;
  topics?: T;
  startDate?: T;
  endDate?: T;
  durationDays?: T;
  durationHours?: T;
  deliveryMode?: T;
  level?: T;
  venue?: T;
  instructionLanguages?: T;
  targetAudience?: T;
  participantCountries?: T;
  quota?: T;
  applicationRequirements?: T;
  applicationDeadline?: T;
  applicationTarget?:
    | T
    | {
        type?: T;
        url?: T;
        portalPath?: T;
        email?: T;
        contactUnit?: T;
      };
  objective?: T;
  learningOutcomes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  schedule?:
    | T
    | {
        dayLabel?: T;
        sessions?:
          | T
          | {
              time?: T;
              title?: T;
              type?: T;
              trainer?: T;
              id?: T;
            };
        id?: T;
      };
  trainers?:
    | T
    | {
        name?: T;
        titleAndRole?: T;
        organization?: T;
        photo?: T;
        id?: T;
      };
  assessmentMethod?: T;
  usesSimulation?: T;
  simulationSystems?: T;
  hasFieldExercise?: T;
  certificateType?: T;
  certificateConditions?: T;
  issuingBodies?:
    | T
    | {
        name?: T;
        logo?: T;
        id?: T;
      };
  attachments?: T;
  libraryCollectionKey?: T;
  results?:
    | T
    | {
        participantCount?: T;
        summary?: T;
        photos?: T;
        videoUrl?: T;
        hadCertificateCeremony?: T;
        relatedNews?: T;
      };
  coverImage?: T;
  gallery?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "simulation-systems_select".
 */
export interface SimulationSystemsSelect<T extends boolean = true> {
  slug?: T;
  order?: T;
  translationStatus?: T;
  title?: T;
  shortCode?: T;
  summary?: T;
  description?: T;
  useCases?:
    | T
    | {
        text?: T;
        id?: T;
      };
  benefitsForInternational?: T;
  technicalSpecs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  capacity?: T;
  supportsRemote?: T;
  accessLinks?:
    | T
    | {
        audience?: T;
        label?: T;
        url?: T;
        id?: T;
      };
  coverImage?: T;
  gallery?: T;
  videos?:
    | T
    | {
        title?: T;
        url?: T;
        poster?: T;
        captionsUrl?: T;
        transcript?: T;
        id?: T;
      };
  relatedTopics?: T;
  usageInTraining?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "virtual-classrooms_select".
 */
export interface VirtualClassroomsSelect<T extends boolean = true> {
  title?: T;
  training?: T;
  roomStatus?: T;
  platform?: T;
  startsAt?: T;
  endsAt?: T;
  joinWindowMinutes?: T;
  instructions?: T;
  meetingUrl?: T;
  meetingId?: T;
  moderatorPassword?: T;
  attendeePassword?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  slug?: T;
  reviewStatus?: T;
  kind?: T;
  category?: T;
  featured?: T;
  expiresAt?: T;
  translationStatus?: T;
  publishedAt?: T;
  title?: T;
  summary?: T;
  content?: T;
  coverImage?: T;
  gallery?: T;
  videoUrl?: T;
  relatedTrainings?: T;
  relatedTopics?: T;
  countries?: T;
  attachments?: T;
  isProjectOutput?: T;
  project?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "international-guide_select".
 */
export interface InternationalGuideSelect<T extends boolean = true> {
  slug?: T;
  order?: T;
  translationStatus?: T;
  sectionKey?: T;
  title?: T;
  summary?: T;
  content?: T;
  image?: T;
  attachments?: T;
  countries?: T;
  countryNotes?:
    | T
    | {
        country?: T;
        note?: T;
        id?: T;
      };
  links?:
    | T
    | {
        label?: T;
        url?: T;
        isExternal?: T;
        id?: T;
      };
  relatedFaqs?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  group?: T;
  order?: T;
  translationStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  pageType?: T;
  parent?: T;
  translationStatus?: T;
  publishedAt?: T;
  title?: T;
  subtitle?: T;
  heroImage?: T;
  layout?:
    | T
    | {
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              media?: T;
              caption?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        statsBlock?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        peopleBlock?:
          | T
          | {
              heading?: T;
              people?:
                | T
                | {
                    name?: T;
                    role?: T;
                    unit?: T;
                    photo?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        partnersBlock?:
          | T
          | {
              heading?: T;
              partners?:
                | T
                | {
                    name?: T;
                    logo?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timelineBlock?:
          | T
          | {
              heading?: T;
              entries?:
                | T
                | {
                    year?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBlock?:
          | T
          | {
              heading?: T;
              text?: T;
              target?: T;
              href?: T;
              buttonLabel?: T;
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              heading?: T;
              faqs?: T;
              id?: T;
              blockName?: T;
            };
        contactBlock?:
          | T
          | {
              showMap?: T;
              showForm?: T;
              form?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-albums_select".
 */
export interface GalleryAlbumsSelect<T extends boolean = true> {
  slug?: T;
  albumType?: T;
  date?: T;
  translationStatus?: T;
  title?: T;
  description?: T;
  coverImage?: T;
  images?: T;
  videos?:
    | T
    | {
        title?: T;
        url?: T;
        poster?: T;
        durationSeconds?: T;
        captionsUrl?: T;
        id?: T;
      };
  relatedTraining?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  mediaType?: T;
  isDecorative?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-files_select".
 */
export interface DocumentFilesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  documentType?: T;
  language?: T;
  version?: T;
  accessLevel?: T;
  isArchived?: T;
  license?: T;
  copyrightHolder?: T;
  humanFileSize?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "library-resources_select".
 */
export interface LibraryResourcesSelect<T extends boolean = true> {
  slug?: T;
  reviewStatus?: T;
  accessLevel?: T;
  resourceType?: T;
  publicationYear?: T;
  featured?: T;
  downloads?: T;
  uploadedBy?: T;
  translationStatus?: T;
  publishedAt?: T;
  title?: T;
  description?: T;
  author?: T;
  institution?: T;
  language?: T;
  countries?: T;
  keywords?: T;
  identifier?: T;
  relatedTrainings?: T;
  relatedProjects?: T;
  topics?: T;
  videoFile?: T;
  allowVideoDownload?: T;
  videoDuration?: T;
  captionsUrl?: T;
  gallery?: T;
  file?: T;
  externalUrl?: T;
  fileFormat?: T;
  fileSize?: T;
  version?: T;
  license?: T;
  copyrightHolder?: T;
  coverImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  slug?: T;
  isPrimary?: T;
  translationStatus?: T;
  title?: T;
  symbol?: T;
  startDate?: T;
  endDate?: T;
  nationalCounterpart?: T;
  partners?:
    | T
    | {
        name?: T;
        logo?: T;
        url?: T;
        id?: T;
      };
  focusCountries?: T;
  objective?: T;
  capacityStatement?: T;
  externalUrl?: T;
  logos?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-requests_select".
 */
export interface FormRequestsSelect<T extends boolean = true> {
  submissionType?: T;
  status?: T;
  fullName?: T;
  email?: T;
  organization?: T;
  country?: T;
  subject?: T;
  message?: T;
  relatedTraining?: T;
  consentAcceptedAt?: T;
  consentSnapshot?: T;
  locale?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  role?: T;
  accountStatus?: T;
  unit?: T;
  preferredAdminLanguage?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search-index_select".
 */
export interface SearchIndexSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  consentText?: T;
  retentionDays?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteShortName?: string | null;
  tagline?: string | null;
  defaultDescription?: string | null;
  /**
   * Spec 10.2 — logo usage must follow FAO/MAF/OGM visibility rules.
   */
  logos?: {
    primary?: (number | null) | Media;
    primaryDark?: (number | null) | Media;
    favicon?: (number | null) | Media;
    ogImage?: (number | null) | Media;
    partnerLogos?:
      | {
          name: string;
          image: number | Media;
          url?: string | null;
          order?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    organizationName?: string | null;
    address?: string | null;
    phone?: string | null;
    fax?: string | null;
    email?: string | null;
    trainingEmail?: string | null;
    map?: {
      latitude?: number | null;
      longitude?: number | null;
      directions?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      /**
       * Shown instead of the embedded map before cookie consent (spec 12.3).
       */
      staticMapImage?: (number | null) | Media;
    };
    socialLinks?:
      | {
          platform: string;
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Spec 10.1 — displayed in the project visibility strip.
   */
  primaryProject?: (number | null) | Project;
  /**
   * e.g. donor/cooperation acknowledgement, shown site-wide in the footer.
   */
  visibilityStatement?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cookieBanner?: {
    enabled?: boolean | null;
    text?: string | null;
    policyPage?: (number | null) | Page;
    allowPreferenceManagement?: boolean | null;
  };
  privacyNoticePage?: (number | null) | Page;
  /**
   * Spec 13 — WCAG 2.2 AA conformance statement and feedback channel.
   */
  accessibilityStatementPage?: (number | null) | Page;
  analytics?: {
    enabled?: boolean | null;
    /**
     * Required by spec 12.3. Do not disable.
     */
    anonymizeIp?: boolean | null;
    requiresConsent?: boolean | null;
  };
  maintenanceMode?: {
    enabled?: boolean | null;
    message?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The menu tree is identical across locales; only labels are translated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Max 8 top-level items to keep mobile navigation readable.
   */
  mainMenu?:
    | {
        label: string;
        /**
         * Fill in when the label alone is ambiguous (WCAG 2.2 — 2.4.4).
         */
        ariaLabel?: string | null;
        type: 'page' | 'route' | 'library' | 'portal' | 'external' | 'anchor';
        page?: (number | null) | Page;
        route?:
          | (
              | 'home'
              | 'training-topics'
              | 'training-programs'
              | 'training-calendar'
              | 'simulation-centre'
              | 'library'
              | 'news'
              | 'gallery'
              | 'international-guide'
              | 'projects'
              | 'contact'
              | 'search'
            )
          | null;
        /**
         * Base URL comes from External Services. Enter only the path.
         */
        path?: string | null;
        url?: string | null;
        children?:
          | {
              label: string;
              /**
               * Fill in when the label alone is ambiguous (WCAG 2.2 — 2.4.4).
               */
              ariaLabel?: string | null;
              type: 'page' | 'route' | 'library' | 'portal' | 'external' | 'anchor';
              page?: (number | null) | Page;
              route?:
                | (
                    | 'home'
                    | 'training-topics'
                    | 'training-programs'
                    | 'training-calendar'
                    | 'simulation-centre'
                    | 'library'
                    | 'news'
                    | 'gallery'
                    | 'international-guide'
                    | 'projects'
                    | 'contact'
                    | 'search'
                  )
                | null;
              /**
               * Base URL comes from External Services. Enter only the path.
               */
              path?: string | null;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        highlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  footerColumns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              /**
               * Fill in when the label alone is ambiguous (WCAG 2.2 — 2.4.4).
               */
              ariaLabel?: string | null;
              type: 'page' | 'route' | 'library' | 'portal' | 'external' | 'anchor';
              page?: (number | null) | Page;
              route?:
                | (
                    | 'home'
                    | 'training-topics'
                    | 'training-programs'
                    | 'training-calendar'
                    | 'simulation-centre'
                    | 'library'
                    | 'news'
                    | 'gallery'
                    | 'international-guide'
                    | 'projects'
                    | 'contact'
                    | 'search'
                  )
                | null;
              /**
               * Base URL comes from External Services. Enter only the path.
               */
              path?: string | null;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Privacy notice, cookie policy, accessibility statement.
   */
  footerLegalLinks?:
    | {
        label: string;
        /**
         * Fill in when the label alone is ambiguous (WCAG 2.2 — 2.4.4).
         */
        ariaLabel?: string | null;
        type: 'page' | 'route' | 'library' | 'portal' | 'external' | 'anchor';
        page?: (number | null) | Page;
        route?:
          | (
              | 'home'
              | 'training-topics'
              | 'training-programs'
              | 'training-calendar'
              | 'simulation-centre'
              | 'library'
              | 'news'
              | 'gallery'
              | 'international-guide'
              | 'projects'
              | 'contact'
              | 'search'
            )
          | null;
        /**
         * Base URL comes from External Services. Enter only the path.
         */
        path?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  quickAccess?:
    | {
        label: string;
        /**
         * Fill in when the label alone is ambiguous (WCAG 2.2 — 2.4.4).
         */
        ariaLabel?: string | null;
        type: 'page' | 'route' | 'library' | 'portal' | 'external' | 'anchor';
        page?: (number | null) | Page;
        route?:
          | (
              | 'home'
              | 'training-topics'
              | 'training-programs'
              | 'training-calendar'
              | 'simulation-centre'
              | 'library'
              | 'news'
              | 'gallery'
              | 'international-guide'
              | 'projects'
              | 'contact'
              | 'search'
            )
          | null;
        /**
         * Base URL comes from External Services. Enter only the path.
         */
        path?: string | null;
        url?: string | null;
        description?: string | null;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The homepage hero and the featured-training strip. Content itself lives in its own collections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero?: {
    /**
     * Small line above the headline, e.g. “In cooperation with FAO and OGM”.
     */
    eyebrow?: string | null;
    /**
     * The page’s single H1. Falls back to the site name from Site Settings.
     */
    headline?: string | null;
    subheadline?: string | null;
    /**
     * At least 1920×900 recommended. The image is decorative; do not bake text into it (WCAG 2.2 — 1.4.5). Falls back to the corporate green gradient.
     */
    backgroundImage?: (number | null) | Media;
    /**
     * Keeps the headline readable on any photo. The 65% floor is measured and also enforced in code.
     */
    overlay?: {
      opacity?: number | null;
      /**
       * The base overlay always applies; the gradient only darkens the text side further.
       */
      style?: ('gradient' | 'solid') | null;
    };
    primaryCta?: {
      /**
       * The button is hidden when this is empty.
       */
      label?: string | null;
      type?: ('page' | 'route' | 'library' | 'portal' | 'external') | null;
      page?: (number | null) | Page;
      route?:
        | (
            | 'home'
            | 'training-topics'
            | 'training-programs'
            | 'training-calendar'
            | 'simulation-centre'
            | 'library'
            | 'news'
            | 'gallery'
            | 'international-guide'
            | 'projects'
            | 'contact'
            | 'search'
          )
        | null;
      /**
       * Base URL comes from External Services. Enter only the path.
       */
      path?: string | null;
      url?: string | null;
    };
    secondaryCta?: {
      /**
       * The button is hidden when this is empty.
       */
      label?: string | null;
      type?: ('page' | 'route' | 'library' | 'portal' | 'external') | null;
      page?: (number | null) | Page;
      route?:
        | (
            | 'home'
            | 'training-topics'
            | 'training-programs'
            | 'training-calendar'
            | 'simulation-centre'
            | 'library'
            | 'news'
            | 'gallery'
            | 'international-guide'
            | 'projects'
            | 'contact'
            | 'search'
          )
        | null;
      /**
       * Base URL comes from External Services. Enter only the path.
       */
      path?: string | null;
      url?: string | null;
    };
    /**
     * Rendered as a glass panel on the RIGHT of the hero. Omitted entirely when empty.
     */
    highlights?:
      | {
          /**
           * Short and bold, e.g. “14+ participating countries”.
           */
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Rendered as a strip under the hero. Omitted entirely when empty.
     */
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  featuredTrainings?: {
    /**
     * Falls back to the default UI translation when empty.
     */
    title?: string | null;
    intro?: string | null;
    /**
     * The bento layout adapts to this count. 5 gives the most balanced arrangement.
     */
    limit?: number | null;
    /**
     * Shows the training status field as a badge on each card.
     */
    showStatusBadges?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The digital library and management portal run on subdomains built by another team. These settings drive every outbound link on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "external-services".
 */
export interface ExternalService {
  id: number;
  library: {
    /**
     * With “Coming soon” the menu item is non-clickable and shows an informational notice.
     */
    status: 'live' | 'coming-soon' | 'maintenance' | 'hidden';
    /**
     * No trailing slash. e.g. https://kutuphane.aiftc.org
     */
    baseUrl: string;
    label: string;
    notice?: string | null;
    /**
     * Placeholders: {locale}, {query}, {subject}, {trainingCode}. Agree the format with the library team.
     */
    searchPathTemplate?: string | null;
    subjectPathTemplate?: string | null;
    trainingMaterialsPathTemplate?: string | null;
    /**
     * Adds rel="noopener noreferrer" and a screen-reader hint (WCAG 2.2).
     */
    openInNewTab?: boolean | null;
    /**
     * Anonymous click counter for the reporting in spec 17. No personal data.
     */
    trackClicks?: boolean | null;
    /**
     * Spec 6.1 — quick access to the digital library.
     */
    featuredCollections?:
      | {
          title: string;
          description?: string | null;
          /**
           * e.g. /collections/fire-management
           */
          path: string;
          icon?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  portal: {
    status: 'live' | 'coming-soon' | 'maintenance' | 'hidden';
    baseUrl: string;
    /**
     * The “Staff login” link points here. Authentication happens entirely on the portal.
     */
    loginPath?: string | null;
    applicationPath?: string | null;
    /**
     * Spec 7.3. QR/number verification runs on the portal; the site only redirects.
     */
    certificateVerifyPath?: string | null;
    showStaffLoginInHeader?: boolean | null;
  };
  /**
   * Spec EK-2 general provisions. EK-1 only links to it.
   */
  virtualClassroom?: {
    enabled?: boolean | null;
    baseUrl?: string | null;
    label?: string | null;
  };
  ogm?: {
    url?: string | null;
    legacyPageUrl?: string | null;
  };
  additional?:
    | {
        /**
         * Key used in code
         */
        key: string;
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Page intro and capacity summary. System cards live in their own collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "simulation-center".
 */
export interface SimulationCenter {
  id: number;
  title: string;
  purpose?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  roleInFireTraining?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relationToTraining?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  introVideo?: {
    url?: string | null;
    poster?: (number | null) | Media;
    captionsUrl?: string | null;
  };
  capacityHighlights?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Spec 6.5 — simulation media is served through a CDN.
   */
  cdn?: {
    enabled?: boolean | null;
    baseUrl?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteShortName?: T;
  tagline?: T;
  defaultDescription?: T;
  logos?:
    | T
    | {
        primary?: T;
        primaryDark?: T;
        favicon?: T;
        ogImage?: T;
        partnerLogos?:
          | T
          | {
              name?: T;
              image?: T;
              url?: T;
              order?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        organizationName?: T;
        address?: T;
        phone?: T;
        fax?: T;
        email?: T;
        trainingEmail?: T;
        map?:
          | T
          | {
              latitude?: T;
              longitude?: T;
              directions?: T;
              staticMapImage?: T;
            };
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
      };
  primaryProject?: T;
  visibilityStatement?: T;
  cookieBanner?:
    | T
    | {
        enabled?: T;
        text?: T;
        policyPage?: T;
        allowPreferenceManagement?: T;
      };
  privacyNoticePage?: T;
  accessibilityStatementPage?: T;
  analytics?:
    | T
    | {
        enabled?: T;
        anonymizeIp?: T;
        requiresConsent?: T;
      };
  maintenanceMode?:
    | T
    | {
        enabled?: T;
        message?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainMenu?:
    | T
    | {
        label?: T;
        ariaLabel?: T;
        type?: T;
        page?: T;
        route?: T;
        path?: T;
        url?: T;
        children?:
          | T
          | {
              label?: T;
              ariaLabel?: T;
              type?: T;
              page?: T;
              route?: T;
              path?: T;
              url?: T;
              id?: T;
            };
        highlight?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              ariaLabel?: T;
              type?: T;
              page?: T;
              route?: T;
              path?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  footerLegalLinks?:
    | T
    | {
        label?: T;
        ariaLabel?: T;
        type?: T;
        page?: T;
        route?: T;
        path?: T;
        url?: T;
        id?: T;
      };
  quickAccess?:
    | T
    | {
        label?: T;
        ariaLabel?: T;
        type?: T;
        page?: T;
        route?: T;
        path?: T;
        url?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        subheadline?: T;
        backgroundImage?: T;
        overlay?:
          | T
          | {
              opacity?: T;
              style?: T;
            };
        primaryCta?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              route?: T;
              path?: T;
              url?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              route?: T;
              path?: T;
              url?: T;
            };
        highlights?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  featuredTrainings?:
    | T
    | {
        title?: T;
        intro?: T;
        limit?: T;
        showStatusBadges?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "external-services_select".
 */
export interface ExternalServicesSelect<T extends boolean = true> {
  library?:
    | T
    | {
        status?: T;
        baseUrl?: T;
        label?: T;
        notice?: T;
        searchPathTemplate?: T;
        subjectPathTemplate?: T;
        trainingMaterialsPathTemplate?: T;
        openInNewTab?: T;
        trackClicks?: T;
        featuredCollections?:
          | T
          | {
              title?: T;
              description?: T;
              path?: T;
              icon?: T;
              id?: T;
            };
      };
  portal?:
    | T
    | {
        status?: T;
        baseUrl?: T;
        loginPath?: T;
        applicationPath?: T;
        certificateVerifyPath?: T;
        showStaffLoginInHeader?: T;
      };
  virtualClassroom?:
    | T
    | {
        enabled?: T;
        baseUrl?: T;
        label?: T;
      };
  ogm?:
    | T
    | {
        url?: T;
        legacyPageUrl?: T;
      };
  additional?:
    | T
    | {
        key?: T;
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "simulation-center_select".
 */
export interface SimulationCenterSelect<T extends boolean = true> {
  title?: T;
  purpose?: T;
  roleInFireTraining?: T;
  relationToTraining?: T;
  heroImage?: T;
  introVideo?:
    | T
    | {
        url?: T;
        poster?: T;
        captionsUrl?: T;
      };
  capacityHighlights?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  cdn?:
    | T
    | {
        enabled?: T;
        baseUrl?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'training-topics';
          value: number | TrainingTopic;
        } | null)
      | ({
          relationTo: 'training-programs';
          value: number | TrainingProgram;
        } | null)
      | ({
          relationTo: 'news';
          value: number | News;
        } | null)
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'library-resources';
          value: number | LibraryResource;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}